Clean up code
timehop/nimbus-unity pull request #25
Opened 2021-06-24 21:26 UTC by inderdhir

2021-06-24 21:28 UTC, inderdhir commented on package/Runtime/Plugins/iOS/NimbusManager.swift
> +        NimbusAdManager.user = user
Equivalent but ideally all our pubs always go through the NimbusAdManager

2021-06-24 21:28 UTC, inderdhir commented on package/Runtime/Plugins/iOS/NimbusManager.swift
> -        (Nimbus.shared.renderers[.forAuctionType(.video)] as? NimbusVideoAdRenderer)?.showMuteButton = false // false by default
false by default

2021-06-24 21:32 UTC, marcsantiago requested changes
No so much a change, but before merging you need to ensure everything builds in Unity and that all the functionality is the same, @brugg knows what to look for so work with him to ensure it's all working as intended. @brugg let me know when there is another build in test flight so that I can test these changes as well.

2021-06-24 23:05 UTC, brugg approved these changes

2021-06-24 23:05 UTC, brugg commented
@marcsantiago the build was published to TestFlight. v0.0.3.

2021-06-25 14:20 UTC, marcsantiago approved these changes

2021-06-25 14:20 UTC, marcsantiago commented
> @marcsantiago the build was published to TestFlight. v0.0.3.

Thanks @brugg downloaded and tested. Everything looks the same, this is good to go.

2021-06-25 14:24 UTC, merged